const lexicalTheme = {
  paragraph: "leading-6",
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
  },
  list: {
    ul: "list-disc pl-4 ml-1",
    ol: "list-decimal pl-4 ml-1",
    listitem: "leading-5",
    nested: { listitem: "list-none" },
  },
  code: "font-mono text-xs rounded p-2 my-1 block overflow-x-auto whitespace-pre editor-code-block",
  codeHighlight: {
    comment: "editor-token-comment italic",
    prolog: "editor-token-comment",
    doctype: "editor-token-comment",
    cdata: "editor-token-comment",
    keyword: "editor-token-keyword",
    atrule: "editor-token-keyword",
    important: "editor-token-keyword",
    regex: "editor-token-keyword",
    selector: "editor-token-string",
    string: "editor-token-string",
    char: "editor-token-string",
    inserted: "editor-token-string",
    "class-name": "editor-token-class",
    class: "editor-token-class",
    function: "editor-token-function",
    builtin: "editor-token-function",
    number: "editor-token-number",
    boolean: "editor-token-number",
    constant: "editor-token-number",
    symbol: "editor-token-number",
    deleted: "editor-token-property",
    property: "editor-token-property",
    tag: "editor-token-property",
    namespace: "editor-token-property",
    entity: "editor-token-property",
    attr: "editor-token-property",
    variable: "editor-token-property",
    operator: "editor-token-operator",
    url: "editor-token-operator",
    punctuation: "editor-token-punctuation",
  },
};

export default lexicalTheme;
